theme: jekyll-theme-leap-day
title: ShanghaiTech Automation and Robotics Datasets
description: Datasets collected by the ShanghaiTech Automation and Robotics Center (STAR Center), School of Information Science and Technology (SIST), ShanghaiTech University.
github:
  is_project_page: false
